import os

from conan import ConanFile
from conan.errors import ConanInvalidConfiguration
from conan.tools.build import check_min_cppstd
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import copy, get, rmdir
from conan.tools.intel import IntelCC

required_conan_version = ">=2"


class PreciceConan(ConanFile):
    name = "precice"
    package_type = "shared-library"
    license = "LGPL-3.0-or-later"
    homepage = "https://precice.org"
    url = "https://github.com/precice/precice"
    description = (
        "preCICE (Precise Code Interaction Coupling Environment) is a coupling "
        "library for partitioned multi-physics simulations, including "
        "fluid-structure interaction and conjugate heat transfer."
    )
    topics = ("coupling", "multiphysics", "fsi", "mpi", "hpc")

    settings = "os", "arch", "compiler", "build_type", "fortran_compiler"
    options = {
        "mpi": [True, False],
        "bindings_c": [True, False],
        "bindings_fortran": [True, False],
        "tools": [True, False],
        "hide_symbols": [True, False],
    }
    default_options = {
        "mpi": True,
        "bindings_c": True,
        "bindings_fortran": True,
        "tools": True,
        "hide_symbols": False,
        # preCICE is compiled with BOOST_ALL_DYN_LINK, so Boost must be shared.
        "boost/*:shared": True,
    }

    def layout(self):
        cmake_layout(self, src_folder="src")

    def configure(self):
        if not self.options.bindings_fortran:
            self.settings.rm_safe("fortran_compiler")

    def requirements(self):
        self.requires("boost/1.90.0")
        self.requires("eigen/5.0.1")
        self.requires("libxml2/2.15.3")

    def build_requirements(self):
        self.tool_requires("cmake/[>=3.22 <5]")

    def validate(self):
        if self.settings.os not in ("Linux", "Windows"):
            raise ConanInvalidConfiguration(
                "The precice recipe currently supports Linux and Windows only."
            )
        check_min_cppstd(self, 17)

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)

    def generate(self):
        # MPI is not a Conan package here: it is provided by Intel oneAPI.
        # On Linux the oneAPI environment is registered through IntelCC so that
        # the MPI wrappers are on PATH during the build. On Windows the
        # environment is inherited from the "Intel oneAPI command prompt" that
        # `conan create` must be launched from.
        if self.settings.os == "Linux" and self.settings.compiler == "intel-cc":
            IntelCC(self).generate()

        deps = CMakeDeps(self)
        deps.generate()

        tc = CMakeToolchain(self)
        tc.cache_variables["CMAKE_INSTALL_LIBDIR"] = "lib"
        tc.cache_variables["CMAKE_INSTALL_BINDIR"] = "bin"
        # Prefer the config files generated by CMakeDeps over CMake's own
        # find modules (Boost, Eigen3, LibXml2 are all consumed as CONFIG).
        tc.cache_variables["CMAKE_FIND_PACKAGE_PREFER_CONFIG"] = True
        # preCICE validates its dependencies with try_compile (cmake/Validation.cmake).
        # if not specified, try compile defaults to Debug
        tc.cache_variables["CMAKE_TRY_COMPILE_CONFIGURATION"] = str(
            self.settings.build_type
        )
        # cmake/DetectGitRevision.cmake adds a build step that runs
        # `git describe` in the source folder to stamp the revision into
        # versions.cpp. We build from a release tarball, so that folder is not a
        # git repository and git writes "fatal: not a git repository" to stderr.
        # The build still succeeds, but the message aborts the TeamCity job
        # ("fatal:" is a build failure condition). Hiding Git makes preCICE
        # configure the fallback versions.cpp instead.
        tc.cache_variables["CMAKE_DISABLE_FIND_PACKAGE_Git"] = True

        tc.cache_variables["PRECICE_FEATURE_MPI_COMMUNICATION"] = self.options.mpi
        tc.cache_variables["PRECICE_BINDINGS_C"] = self.options.bindings_c
        tc.cache_variables["PRECICE_BINDINGS_FORTRAN"] = self.options.bindings_fortran
        tc.cache_variables["PRECICE_BUILD_TOOLS"] = self.options.tools
        tc.cache_variables["PRECICE_HIDE_SYMBOLS"] = self.options.hide_symbols
        # Unused features, each of which would pull in an extra dependency.
        tc.cache_variables["PRECICE_FEATURE_PETSC_MAPPING"] = False
        tc.cache_variables["PRECICE_FEATURE_GINKGO_MAPPING"] = False
        tc.cache_variables["PRECICE_FEATURE_KOKKOS_KERNELS_MAPPING"] = False
        tc.cache_variables["PRECICE_FEATURE_PYTHON_ACTIONS"] = False
        tc.cache_variables["PRECICE_FEATURE_PROFILING_COMPRESSION"] = False
        # Packaging is done by Conan, not by CPack.
        tc.cache_variables["PRECICE_CONFIGURE_PACKAGE_GENERATION"] = False
        tc.cache_variables["BUILD_TESTING"] = False

        if self.settings.os == "Windows":
            # preCICE requires standard-conforming template parsing with MSVC.
            tc.extra_cxxflags.append("/permissive-")
            fortran = self.settings.get_safe("fortran_compiler")
            if self.options.bindings_fortran and fortran in ("ifx", "ifort"):
                # Match the C symbol names the Fortran bindings expect. These
                # flags are specific to the Intel Fortran compilers.
                tc.cache_variables["CMAKE_Fortran_FLAGS"] = (
                    "/names:lowercase /assume:underscore"
                )

        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

        copy(
            self,
            "LICENSE",
            src=self.source_folder,
            dst=os.path.join(self.package_folder, "licenses"),
        )

        rmdir(self, os.path.join(self.package_folder, "lib", "cmake"))
        rmdir(self, os.path.join(self.package_folder, "lib", "pkgconfig"))
        # Contains the examples, man pages and other documentation.
        rmdir(self, os.path.join(self.package_folder, "share"))

    def package_info(self):
        self.cpp_info.set_property("cmake_file_name", "precice")
        self.cpp_info.set_property("cmake_target_name", "precice::precice")
        self.cpp_info.set_property("pkg_config_name", "libprecice")

        self.cpp_info.libs = ["precice"]
        self.cpp_info.requires = [
            "boost::log",
            "boost::log_setup",
            "boost::program_options",
            "boost::thread",
            "boost::unit_test_framework",
            "eigen::eigen3",
            "libxml2::libxml2",
        ]
        # preCICE headers are included as <precice/precice.hpp>, while the
        # installed target additionally exposes include/precice directly.
        self.cpp_info.includedirs = ["include", os.path.join("include", "precice")]

        if self.settings.os == "Windows":
            self.cpp_info.system_libs.append("ws2_32")
        else:
            self.cpp_info.system_libs.extend(["pthread", "dl", "m"])
