FROM containers.deltares.nl/mcr-proxy/windows/server:ltsc2025

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]

RUN reg add "HKLM\SYSTEM\CurrentControlSet\Control\FileSystem" /v "LongPathsEnabled" /t REG_DWORD /d 1 /f

SHELL ["cmd", "/S", "/C"]

ADD vs_Community.exe C:/

RUN (start /w vs_community.exe --passive --wait --noUpdateInstaller --norestart --nocache \
    --installPath "C:\\Program Files\\Microsoft Visual Studio\\17\\Community" \
    --add Microsoft.VisualStudio.Workload.NativeDesktop;includeRecommended \
    --add Microsoft.VisualStudio.Component.Windows11SDK.26100 \
    --add Microsoft.VisualStudio.Component.VC.ATLMFC \
    --add Microsoft.VisualStudio.Component.VC.CLI.Support \
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 \
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 \
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 \
    --remove Microsoft.VisualStudio.Component.Windows81SDK \
    || IF "%ERRORLEVEL%"=="3010" EXIT 0)

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]

# Install the Intel toolkits
ADD intel-fortran-compiler-2025.3.1.15_offline.exe C:/
RUN Start-Process -FilePath "C:\intel-fortran-compiler-2025.3.1.15_offline.exe" -ArgumentList "--silent", "-a", "--action", "install", "--eula=accept", "-p=NEED_VS2022_INTEGRATION=1", "-s" -Wait

ADD intel-onemkl-2025.3.0.460_offline.exe C:/
RUN Start-Process -FilePath "C:\intel-onemkl-2025.3.0.460_offline.exe" -ArgumentList "--silent", "-a", "--action", "install", "--eula=accept", "-p=NEED_VS2022_INTEGRATION=1", "-s" -Wait

ADD intel-mpi-2021.17.1.14_offline.exe C:/
RUN Start-Process -FilePath "C:\intel-mpi-2021.17.1.14_offline.exe" -ArgumentList "--silent", "-a", "--action", "install", "--eula=accept", "-s" -Wait

# RUN Remove intel and visual studio executables
RUN Remove-Item C:\*.exe"

# Install Chocolatey and required packages
# Install cmake 4.x.y, python 3.12.x, git and ninja

RUN powershell.exe -Command \
    Set-ExecutionPolicy Bypass -Scope Process -Force; \
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
    [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}; \
    (New-Object System.Net.WebClient).DownloadFile('https://community.chocolatey.org/install.ps1', 'choco_install.ps1'); \
    ./choco_install.ps1; \
	del choco_install.ps1; \
	choco install cmake git ninja nano -y --no-progress; \
	choco install python --version='3.12.10' -y --no-progress

# Some environment variables

ENV ONEAPI_ROOT="C:\\Program Files (x86)\\Intel\\oneAPI\\"
ENV VS2022INSTALLDIR="C:\Program Files\Microsoft Visual Studio\17\Community"

# Define the entry point for the docker container.
# This entry point starts the developer command prompt and launches the PowerShell shell.

COPY set-env-vs2022.cmd C:\\set-env-vs2022.cmd
ENTRYPOINT ["cmd.exe", "/k", "C:\\set-env-vs2022.cmd"]
