FROM containers.deltares.nl/mcr-proxy/windows/server:ltsc2025

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]

RUN reg add "HKLM\SYSTEM\CurrentControlSet\Control\FileSystem" /v "LongPathsEnabled" /t REG_DWORD /d 1 /f

SHELL ["cmd", "/S", "/C"]

ADD vs_Community.exe C:/

RUN (start /w vs_community.exe --passive --wait --noUpdateInstaller --norestart --nocache \
    --installPath "C:\\Program Files\\Microsoft Visual Studio\\17\\Community" \
    --add Microsoft.VisualStudio.Workload.NativeDesktop;includeRecommended \
    --add Microsoft.VisualStudio.Component.Windows11SDK.26100 \
    --add Microsoft.VisualStudio.Component.VC.ATLMFC \
    --add Microsoft.VisualStudio.Component.VC.CLI.Support \
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 \
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 \
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 \
    --remove Microsoft.VisualStudio.Component.Windows81SDK \
    || IF "%ERRORLEVEL%"=="3010" EXIT 0)

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]

# Install the Intel toolkits
ADD w_fortran-compiler_p_2024.2.1.81_offline.exe C:/
RUN Start-Process -FilePath "C:\w_fortran-compiler_p_2024.2.1.81_offline.exe" -ArgumentList "--silent", "-a", "--action", "install", "--eula=accept", "-p=NEED_VS2022_INTEGRATION=1", "-s" -Wait

ADD w_onemkl_p_2024.2.2.16_offline.exe C:/
RUN Start-Process -FilePath "C:\w_onemkl_p_2024.2.2.16_offline.exe" -ArgumentList "--silent", "-a", "--action", "install", "--eula=accept", "-p=NEED_VS2022_INTEGRATION=1", "-s" -Wait

ADD w_mpi_oneapi_p_2021.13.1.768_offline.exe C:/
RUN Start-Process -FilePath "C:\w_mpi_oneapi_p_2021.13.1.768_offline.exe" -ArgumentList "--silent", "-a", "--action", "install", "--eula=accept", "-s" -Wait

# RUN Remove intel and visual studio executables
RUN Remove-Item C:\*.exe"

# Install CMake
ADD cmake-3.31.0-rc1-windows-x86_64.msi C:\\cmake-3.31.0-rc1-windows-x86_64.msi
RUN Start-Process msiexec -Wait -ArgumentList '/i C:\\cmake-3.31.0-rc1-windows-x86_64.msi /qn'
RUN setx /M PATH $($Env:PATH + ';C:\\Program Files\\CMake\\bin')
RUN Remove-Item C:\\cmake-3.31.0-rc1-windows-x86_64.msi

ENV ONEAPI_ROOT="C:\\Program Files (x86)\\Intel\\oneAPI\\"
ENV VS2022INSTALLDIR="C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\Community\\"

# Download and install git
ADD Git-2.47.0-64-bit.exe C:\\Git-2.47.0-64-bit.exe
RUN Start-Process -FilePath "C:\\Git-2.47.0-64-bit.exe" -ArgumentList "/SILENT" -Wait
RUN Remove-Item C:\\Git-2.47.0-64-bit.exe
RUN setx /M PATH $($Env:PATH + ';C:\\Program Files\\Git\\usr\\bin')

# Install uv
ENV UV_INSTALL_DIR="C:\Program Files\uv\install"
RUN irm https://astral.sh/uv/0.11.11/install.ps1 | iex

ENV UV_PYTHON_INSTALL_DIR="C:\Program Files\uv\python" \
    UV_TOOL_DIR="C:\Program Files\uv\tools" \
    UV_PYTHON_BIN_DIR="C:\Program Files\uv\bin" \
    UV_TOOL_BIN_DIR="C:\Program Files\uv\bin"

# Install python and conan
RUN setx /M PATH \"C:\Program Files\uv\bin;C:\Program Files\uv\install;$env:PATH\"
RUN uv python install 3.12 --default
RUN uv tool install 'conan ~= 2.28.1'

# Copy the setup script into the container
COPY set-env-vs2022.cmd C:\\set-env-vs2022.cmd

# Set the default command to run the setup script
CMD ["cmd", "/S", "/C", "C:\\set-env-vs2022.cmd"]