<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>DFlowFM.IO</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>DFlowFM.IO.NET</PackageId>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Description>.NET library for reading, writing, validating and migrating D-Flow FM model files.</Description>
  </PropertyGroup>

  <PropertyGroup>
    <DFlowFM_IO_NativeLibrary Condition="'$(DFlowFM_IO_NativeLibrary)' == ''">$(MSBuildThisFileDirectory)..\..\..\..\..\**\dflowfm_io_api.dll</DFlowFM_IO_NativeLibrary>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\build\DFlowFM.IO.NET.targets" Visible="false">
      <Pack>true</Pack>
      <PackagePath>build\</PackagePath>
    </None>
    <None Include="$(DFlowFM_IO_NativeLibrary)" Visible="false">
      <Pack>true</Pack>
      <PackagePath>runtimes\win-x64\native\%(Filename)%(Extension)</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>win-x64\native\%(Filename)%(Extension)</TargetPath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\..\..\..\json\mdu.json" Visible="false"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DFlowFM.IO.NET.Generators\DFlowFM.IO.NET.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"/>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>DFlowFM.IO.NET.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
