<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>DFlowFM.IO.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit"/>
    <PackageReference Include="NUnit.Analyzers"/>
    <PackageReference Include="NUnit3TestAdapter"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DFlowFM.IO.NET\DFlowFM.IO.NET.csproj"/>
  </ItemGroup>

</Project>